name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install libarchive and liblzma
      run: sudo apt install git g++ make libarchive-dev liblzma-dev
    - name: make
      run: make
