name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install libarchive
      run: sudo apt install libarchive-dev -y

    - name: Compile via make cmd
      run: make -j{nproc}
